# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin "quill", to: "https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.js"
pin "quill/core", to: "https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.core.js"
pin "@tiptap", to: "https://esm.sh/@tiptap/core"
pin "@tiptap/document", to: "https://esm.sh/@tiptap/extension-document"
pin "@tiptap/paragraph", to: "https://esm.sh/@tiptap/extension-paragraph"
pin "@tiptap/image", to: "https://esm.sh/@tiptap/extension-image"
pin "@tiptap/blockquote", to: "https://esm.sh/@tiptap/extension-blockquote"
pin "@tiptap/bold", to: "https://esm.sh/@tiptap/extension-bold"
pin "@tiptap/italic", to: "https://esm.sh/@tiptap/extension-italic"
pin "@tiptap/link", to: "https://esm.sh/@tiptap/extension-link"
pin "@tiptap/text", to: "https://esm.sh/@tiptap/extension-text"
pin "@tiptap/details", to: "https://esm.sh/@tiptap/extension-details"
pin "@tiptap/underline", to: "https://esm.sh/@tiptap/extension-underline"
pin "@tiptap/strike", to: "https://esm.sh/@tiptap/extension-strike"
pin "@tiptap/placeholder", to: "https://esm.sh/@tiptap/extension-placeholder"
pin "@tiptap/extensions", to: "https://esm.sh/@tiptap/extensions"
pin "@tiptap/listkit", to: "https://esm.sh/@tiptap/extension-list"
pin "@tiptap/heading", to: "https://esm.sh/@tiptap/extension-heading"
pin "@tiptap/draghandle", to: "https://esm.sh/@tiptap/extension-drag-handle"
pin "@tiptap/listtextstyle", to: "https://esm.sh/@tiptap/extension-text-style"

pin "yjs", to: "https://esm.sh/yjs"
pin_all_from "app/javascript/controllers", under: "controllers"
